version: "3.7"
services:

  api:
    build: "./api"
    container_name: api
    network_mode: "bridge"
    restart: always
    ports:
      - 8000:8000
  
  # usuario_prod:
  #   build: "./tuse-api-usuario"
  #   env_file:
  #     - ../tuse-env/env_file.env
  #   container_name: usuario
  #   network_mode: "bridge"
  #   restart: always
  #   ports:
  #     - 8095:8000
  
  #8096 Franquia
